apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: mysubscriptions
scopes:
  # Change to "inventory" to use declarative subscriptions
  - inventory-disabled
spec:
  pubsubname: pubsub
  topic: inventory
  routes:
    rules:
      - match: "event.type == 'widget.v1'"
        path: /widgets
      - match: "event.type == 'gadget.v1'"
        path: /gadgets
    default: /products
